version: '3.8'

services:
  web:
    image: rizadwiandhika/python-articles-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    container_name: web
    hostname: web
    networks:
      - app-network
    ports:
      - 8000:8000
    volumes:
      - web-volume:/usr/src/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: postgres:latest
    container_name: db
    hostname: db
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      - app-network
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:?database password not set}
      - POSTGRES_DB=${DB_NAME:?database does not exist}

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    volumes:
      - redis-volume:/data
    networks:
      - app-network

volumes:
  web-volume:
  db-volume:
  redis-volume:

networks:
  app-network:
    driver: bridge
