version: '3.8'

services:
  web:
    image: rizadwiandhika/django-articles-api:latest
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    container_name: web
    hostname: web
    volumes:
      - web-static-volume:/home/app/web/staticfiles
      - web-media-volume:/home/app/web/mediafiles
    networks:
      - app-network
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis
    deploy:
      restart_policy:
        condition: on-failure

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    hostname: nginx
    ports:
      - 1337:80
    networks:
      - app-network
    volumes:
      - web-static-volume:/home/app/web/staticfiles
      - web-media-volume:/home/app/web/mediafiles
    depends_on:
      - web

  db:
    image: postgres:latest
    container_name: db
    hostname: db
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      - app-network
    env_file:
      - .env.prod

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    volumes:
      - redis-volume:/data
    networks:
      - app-network

volumes:
  web-static-volume:
  web-media-volume:
  db-volume:
  redis-volume:

networks:
  app-network:
    driver: bridge
